AlgoScaleAssesment/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('', include(('account.urls','account'),namespace='account'))
]

account/urls.py
from django.urls import path
from django.conf.urls import url
from account import views

urlpatterns = [
    path('', views.signup, name='signup'),
    path('userlist/',views.UserListView.as_view(),name='home'),
    path('login/',views.login_view,name='login'),
    path('profile/<int:pk>/',views.UserDetailView.as_view(),name='profile'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput(render_value=False),max_length=100)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

account/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.views.generic import ListView,DetailView
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import login, authenticate

from .forms import LoginForm,SignUpForm



from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request,'Please confirm your email address to complete the registration')
            return redirect('/login/')
    else:
        form = SignUpForm()
    return render(request, 'account/signup.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request,'Thank you for your email confirmation. Now you can login your account.')
        return redirect('/login/')
    else:
        messages.error(request,'Activation link is invalid !')
        return redirect('/login/')


class UserListView(ListView):
    model = User
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['object_list'] = context['object_list'].exclude(username=self.request.user.username)
        return context

    def post(self, request, *args, **kwargs):
        user = request.POST.getlist('user')
        if User.objects.filter(id__in=user):
            username = User.objects.filter(id__in=user)[0].username
            User.objects.filter(id__in=user).delete()
            messages.success(request, 'User {} deleted successfully '.format(username) ,extra_tags='alert')
            return HttpResponseRedirect(self.request.path_info)

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if User.objects.filter(username=username):
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/profile/{}'.format(user.id))# Redirect to a success page.
                else:
                    messages.info(request, "Please Activate your account via link sent to your email")
                    return HttpResponseRedirect("/login")
            else:
                messages.error(request, "Wrong Password")
            return HttpResponseRedirect("/login")
        else:
            messages.info(request, "User {} does not exists".format(username) )
            return HttpResponseRedirect("/")
        # return HttpResponseRedirect("/login")
    form=LoginForm()
    return render(request, 'registration/login.html', {'login_form': LoginForm})


class UserDetailView(DetailView):
    model = User
    template_name = "account/profile.html"

account/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}
{% endautoescape %}

account/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>
    {% block title %}
        Articles Page
    {% endblock title %}
        </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    
    {% block additional_css %}
    {% endblock additional_css %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    {% include 'navbar/navbar.html' %}
    
    <div class="container-fluid">

      {% block content %}
      
      {% endblock content %}
      
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script> -->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    {% block additional_js %}
    {% endblock additional_js %}
  </body>
</html>

account/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <h1>Hi {{ user.username }}!</h1>
  <h4>Here are users on boarded</h4>
  <form class="form-group" method="POST" >
    {% if messages %}
      {% include 'messages.html' %}
    {% endif %}
    {% csrf_token %}
    {% include 'account/user-list.html' %}
    <hr>
    <input class="btn btn-danger" value="Delete User" type="submit" role="button">
  </form>
{% else %}
  <p>You are not logged in</p>
  <div>
    <a type="button" href="{% url 'login' %}">login</a>
  </div>
  <div>
    <a type="button" href="{% url 'account:signup' %}">Sign Up</a>
  </div>
{% endif %}
{% endblock %}

account/templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

account/templates/navbar/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">AlgoScale </a>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
          <li><a href="{% url 'account:home' %}">User List</a></li>
          {% comment %} <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Article <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'articles:create-Article' %}">Publish Article</a></li>
              <li><a href="{% url 'articles:list-Article' %}">Show Article</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li> {% endcomment %}
        </ul>
        <!-- {% include 'navbar/search.html' %} -->
        <ul class="nav navbar-nav navbar-right">
          {% include 'navbar/profile.html' %}
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

account/templates/navbar/profile.html
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        {% if user.is_authenticated %}
            {{ user.username }}
                <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><a href="{% url 'account:profile' pk=user.id  %}">User Profile</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li><a href="{% url 'account:login' %}">Login</a></li>
        {% endif %}

account/templates/navbar/search.html
<form class="navbar-form navbar-left">
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>